import { useEffect, useRef, useState } from "react";
import { ArrowUp, Plus } from "lucide-react";

type Message = { role: "user" | "assistant"; text: string };

const suggestions = [
  "Find content for my next project",
  "How does rights management work?",
  "Distribute my film globally",
  "Explore Crayons Loop",
];

export default function AIChat() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, loading]);

  async function send(text = input) {
    const value = text.trim();
    if (!value || loading) return;

    const history = messages.slice(-20);
    setMessages((current) => [...current, { role: "user", text: value }]);
    setInput("");
    setLoading(true);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: value, history }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || `Chat API unavailable (${response.status})`);
      const reply = data.reply || data.message;
      if (!reply) throw new Error("Chat API returned no reply");
      setMessages((current) => [...current, { role: "assistant", text: reply }]);
    } catch {
      setMessages((current) => [
        ...current,
        {
          role: "assistant",
          text: "StreamVista AI chat is not connected to its runtime yet. The interface is ready, but this answer has not been generated by an AI model.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="flex h-screen bg-[#0a0a0a] text-white">
      <aside className="hidden w-[280px] shrink-0 flex-col border-r border-white/10 bg-black p-3 md:flex">
        <button
          onClick={() => setMessages([])}
          className="flex w-full items-center justify-center gap-2 rounded-full bg-white py-3 font-medium text-black transition hover:bg-zinc-200"
        >
          <Plus size={17} /> New chat
        </button>
        <p className="mt-6 px-2 text-xs text-white/40">Recents</p>
        <p className="mt-2 px-2 text-sm text-white/60">No history yet</p>
        <p className="mt-auto text-xs text-white/30">StreamVista (OPC) Private Limited</p>
      </aside>

      <section className="flex min-w-0 flex-1 flex-col">
        <header className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 px-5 sm:px-6">
          <div className="font-semibold">StreamVista AI</div>
          <div className="text-xs text-white/50">Rights-first</div>
        </header>

        <div ref={scrollRef} className="flex-1 overflow-y-auto">
          {messages.length === 0 ? (
            <div className="flex min-h-full flex-col items-center justify-center px-6 py-12 text-center">
              <h1 className="text-4xl font-semibold tracking-tight sm:text-6xl">
                Stories <span className="font-serif italic font-normal">move</span> here.
              </h1>
              <p className="mt-4 text-white/60">One clear path for media: create, discover, distribute.</p>
              <div className="mt-10 grid w-full max-w-2xl grid-cols-1 gap-3 sm:grid-cols-2">
                {suggestions.map((suggestion) => (
                  <button
                    key={suggestion}
                    onClick={() => void send(suggestion)}
                    className="rounded-2xl border border-white/10 p-4 text-left text-sm transition hover:bg-white/5"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="mx-auto w-full max-w-3xl space-y-6 px-5 py-8 sm:px-6">
              {messages.map((message, index) => (
                <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}>
                  <div
                    className={`max-w-[85%] whitespace-pre-wrap rounded-3xl px-5 py-3 text-sm leading-relaxed sm:max-w-[80%] ${
                      message.role === "user" ? "bg-white text-black" : "bg-white/[0.08] text-white"
                    }`}
                  >
                    {message.text}
                  </div>
                </div>
              ))}
              {loading ? <div className="text-sm text-white/40">Thinking...</div> : null}
            </div>
          )}
        </div>

        <div className="shrink-0 border-t border-white/10 p-4">
          <div className="mx-auto flex max-w-3xl items-end gap-3 rounded-[28px] border border-white/10 bg-[#1a1a1a] px-5 py-3">
            <textarea
              value={input}
              onChange={(event) => setInput(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter" && !event.shiftKey) {
                  event.preventDefault();
                  void send();
                }
              }}
              placeholder="Message StreamVista AI..."
              rows={1}
              className="max-h-32 flex-1 resize-none bg-transparent text-sm outline-none placeholder:text-white/35"
            />
            <button
              type="button"
              aria-label="Send message"
              disabled={!input.trim() || loading}
              onClick={() => void send()}
              className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white text-black transition disabled:cursor-not-allowed disabled:opacity-30"
            >
              <ArrowUp size={17} />
            </button>
          </div>
          <p className="mt-2 text-center text-[11px] text-white/30">StreamVista AI can make mistakes. Verify rights before acting.</p>
        </div>
      </section>
    </main>
  );
}
