import { Link } from "react-router-dom";
import { ArrowUpRight, CheckCircle2, Clock3, FileText, ShieldCheck } from "lucide-react";

const timeline = [
  ["AI evaluation", "Civil debt recovery classification completed", "Done"],
  ["Evidence", "Legal notice + user facts captured", "In review"],
  ["Authority", "Provider grievance route requires verification", "Founder action"],
  ["Communication", "No outbound message sent", "Protected"],
];

export default function ComplaintBoxDashboard() {
  return <main className="min-h-screen bg-[#f5f7fb] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link to="/complaint-box" className="font-black tracking-tight">COMPLAINT BOX</Link><div className="flex items-center gap-3"><Link to="/complaint-box/case" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Evaluate case</Link><Link to="/login" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Account</Link></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-700">User dashboard</p><h1 className="mt-2 text-4xl font-black tracking-tight">My cases</h1><p className="mt-2 text-sm text-slate-500">One timeline for evidence, authority routing, communication and resolution.</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><ShieldCheck className="mr-2 inline" size={17}/>Outbound protection active</div></div>
      <section className="mt-7 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">ACTION REQUIRED</span><h2 className="mt-4 text-2xl font-black">HDFC credit card — ₹1,99,834.92</h2><p className="mt-1 text-sm text-slate-500">Civil debt recovery • Notice from Koncept Law Associates</p></div><div className="rounded-xl bg-slate-100 p-3"><FileText size={21}/></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Case status</p><p className="mt-1 font-bold">Evaluation</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Authority</p><p className="mt-1 font-bold">Not yet verified</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Outbound</p><p className="mt-1 font-bold text-emerald-700">Blocked until approval</p></div></div><div className="mt-7 space-y-3">{timeline.map(([title, desc, status], i) => <div key={title} className="flex gap-4 rounded-2xl border border-slate-100 p-4"><div className="mt-1 h-8 w-8 shrink-0 rounded-full bg-slate-950 text-center text-xs font-bold leading-8 text-white">{i + 1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{title}</p><span className="text-xs font-semibold text-slate-500">{status}</span></div><p className="mt-1 text-sm text-slate-500">{desc}</p></div></div>)}</div><Link to="/complaint-box/case" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Continue evaluation <ArrowUpRight size={16}/></Link></article>
      <aside className="space-y-5"><div className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Resolution path</p><div className="mt-5 space-y-4">{["Verify HDFC outstanding", "Verify applicable grievance route", "Review draft", "Approve any send", "Follow up / escalate if eligible", "Confirm resolution"].map((x, i) => <div key={x} className="flex gap-3 text-sm"><span className={`mt-0.5 h-5 w-5 rounded-full ${i < 1 ? "bg-emerald-500" : "border border-slate-300"}`}>{i < 1 && <CheckCircle2 className="text-white" size={20}/>}</span><span className={i < 1 ? "font-semibold" : "text-slate-500"}>{x}</span></div>)}</div></div><div className="rounded-3xl bg-slate-950 p-6 text-white"><Clock3 className="text-cyan-300"/><h3 className="mt-4 font-bold">Next checkpoint</h3><p className="mt-2 text-sm leading-6 text-slate-400">No automatic seven-day legal escalation. The applicable route and response timeline must be verified first.</p></div></aside></section>
    </div></main>;
}
