import { useMemo, useState } from "react";
import { Activity, ArrowUpRight, Bot, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Command, Database, FileCheck2, Filter, Gauge, Globe2, Layers3, Menu, Network, Plus, Search, ShieldCheck, Sparkles, Target, Users2, WalletCards, X } from "lucide-react";

type Priority = "P0" | "P1" | "P2";
type WorkItem = { id: string; title: string; owner: string; department: string; priority: Priority; status: string; value?: string };

const departments = [
  ["00", "Command Center"], ["01", "Company"], ["02", "Revenue"], ["03", "CRM"], ["04", "Product"],
  ["05", "Crayons Bridge"], ["06", "Creator Cloud"], ["07", "Technology"], ["08", "AI"], ["09", "Finance"],
  ["10", "Marketing"], ["11", "Operations"], ["12", "Other Businesses"],
];

const work: WorkItem[] = [
  { id: "REV-104", title: "Close international licensing proposal", owner: "Revenue", department: "02", priority: "P0", status: "Approval", value: "₹18.5L" },
  { id: "CRM-218", title: "Buyer follow-up and qualification", owner: "CRM", department: "03", priority: "P0", status: "Ready", value: "₹7.2L" },
  { id: "CB-076", title: "Rights verification for title package", owner: "Crayons Bridge", department: "05", priority: "P1", status: "Verification" },
  { id: "AI-031", title: "Agent workflow verification", owner: "AI", department: "08", priority: "P1", status: "In progress" },
  { id: "FIN-092", title: "Settlement reconciliation", owner: "Finance", department: "09", priority: "P1", status: "Ready" },
];

function Stat({ label, value, delta, icon: Icon }: { label: string; value: string; delta: string; icon: typeof Gauge }) {
  return <div className="rounded-2xl border border-white/8 bg-white/[0.035] p-4 shadow-[0_20px_60px_rgba(0,0,0,.18)]">
    <div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[.16em] text-slate-500">{label}</span><Icon size={16} className="text-slate-500" /></div>
    <div className="mt-3 flex items-end justify-between gap-3"><strong className="text-2xl font-semibold tracking-tight text-white">{value}</strong><span className="text-xs font-medium text-emerald-400">{delta}</span></div>
  </div>;
}

export default function GlobalBusinessCenter() {
  const [active, setActive] = useState("00");
  const [query, setQuery] = useState("");
  const [mobileNav, setMobileNav] = useState(false);
  const [commandOpen, setCommandOpen] = useState(false);
  const [priority, setPriority] = useState<"ALL" | Priority>("ALL");

  const filteredWork = useMemo(() => work.filter((item) => {
    const matchesPriority = priority === "ALL" || item.priority === priority;
    const q = query.toLowerCase();
    return matchesPriority && (!q || `${item.id} ${item.title} ${item.owner}`.toLowerCase().includes(q));
  }), [priority, query]);

  const activeName = departments.find(([id]) => id === active)?.[1] ?? "Command Center";

  return <div className="min-h-screen bg-[#07090d] text-slate-200">
    <aside className={`fixed inset-y-0 left-0 z-40 w-[270px] border-r border-white/8 bg-[#090c11]/95 backdrop-blur-xl transition-transform ${mobileNav ? "translate-x-0" : "-translate-x-full md:translate-x-0"}`}>
      <div className="flex h-16 items-center gap-3 border-b border-white/8 px-5"><div className="grid h-8 w-8 place-items-center rounded-lg bg-white text-black"><Layers3 size={17}/></div><div><div className="text-sm font-semibold tracking-wide text-white">STREAMVISTA</div><div className="text-[9px] uppercase tracking-[.2em] text-slate-500">Global Business Center</div></div><button onClick={() => setMobileNav(false)} className="ml-auto md:hidden"><X size={18}/></button></div>
      <div className="px-3 py-4"><button onClick={() => setCommandOpen(true)} className="flex w-full items-center gap-2 rounded-xl border border-white/8 bg-white/[.03] px-3 py-2.5 text-left text-xs text-slate-400"><Search size={15}/> Search command center <span className="ml-auto rounded border border-white/10 px-1.5 py-0.5 text-[9px]">⌘K</span></button></div>
      <nav className="space-y-1 px-3 pb-4">{departments.map(([id, name]) => <button key={id} onClick={() => { setActive(id); setMobileNav(false); }} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${active === id ? "bg-white/[.08] text-white" : "text-slate-400 hover:bg-white/[.04] hover:text-slate-200"}`}><span className={`w-6 text-[10px] font-semibold ${active === id ? "text-cyan-300" : "text-slate-600"}`}>{id}</span><span className="text-sm">{name}</span>{active === id && <ChevronRight size={14} className="ml-auto text-slate-500"/>}</button>)}</nav>
      <div className="absolute bottom-0 left-0 right-0 border-t border-white/8 p-3"><div className="rounded-xl bg-white/[.03] p-3"><div className="flex items-center gap-2"><div className="h-7 w-7 rounded-full bg-gradient-to-br from-slate-200 to-slate-600"/><div><div className="text-xs font-medium text-white">Founder Control</div><div className="text-[10px] text-slate-500">Global Admin</div></div><ShieldCheck size={14} className="ml-auto text-emerald-400"/></div></div></div>
    </aside>

    <main className="md:ml-[270px]">
      <header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-white/8 bg-[#07090d]/85 px-4 backdrop-blur-xl md:px-7"><button onClick={() => setMobileNav(true)} className="md:hidden"><Menu size={19}/></button><div className="min-w-0"><div className="text-[10px] uppercase tracking-[.2em] text-slate-500">Executive Workspace / {active}</div><div className="truncate text-sm font-medium text-white">{activeName}</div></div><div className="ml-auto flex items-center gap-2"><button onClick={() => setCommandOpen(true)} className="hidden items-center gap-2 rounded-xl border border-white/8 bg-white/[.03] px-3 py-2 text-xs text-slate-400 sm:flex"><Command size={14}/> Command</button><button className="grid h-9 w-9 place-items-center rounded-xl border border-white/8 bg-white/[.03]"><Activity size={16}/></button><div className="grid h-9 w-9 place-items-center rounded-full border border-white/10 bg-white/[.06] text-xs font-semibold text-white">FA</div></div></header>

      <div className="mx-auto max-w-[1500px] px-4 py-6 md:px-7 md:py-8">
        <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/> SYSTEM OPERATIONAL</div><h1 className="text-3xl font-semibold tracking-[-.03em] text-white md:text-4xl">Good morning, Founder.</h1><p className="mt-2 text-sm text-slate-500">One command center for business, execution and revenue.</p></div><div className="flex items-center gap-2"><button className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300"><Globe2 size={14}/> INR · IST</button><button onClick={() => setCommandOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-xs font-semibold text-black"><Sparkles size={14}/> AI Command</button></div></div>

        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Revenue Today" value="₹4.82L" delta="+18.4%" icon={CircleDollarSign}/><Stat label="Verified Revenue" value="₹38.6L" delta="+12.1%" icon={CheckCircle2}/><Stat label="Expected Pipeline" value="₹1.84Cr" delta="+26.8%" icon={Target}/><Stat label="Active Deals" value="27" delta="6 P0" icon={BriefcaseBusiness}/><Stat label="AI Workforce" value="14 / 18" delta="78% active" icon={Bot}/></section>

        <div className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
          <section className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-white">What needs my attention now?</div><div className="mt-1 text-xs text-slate-500">Revenue-first execution queue · accountable owner visible</div></div><div className="flex items-center gap-2"><button onClick={() => setPriority("ALL")} className={`rounded-lg px-2.5 py-1.5 text-[10px] ${priority === "ALL" ? "bg-white text-black" : "bg-white/[.04] text-slate-400"}`}>ALL</button>{(["P0","P1","P2"] as Priority[]).map(p => <button key={p} onClick={() => setPriority(p)} className={`rounded-lg px-2.5 py-1.5 text-[10px] ${priority === p ? "bg-white text-black" : "bg-white/[.04] text-slate-400"}`}>{p}</button>)}</div></div><div className="mt-4 overflow-hidden rounded-xl border border-white/7"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-white/7 px-4 py-2.5 text-[9px] uppercase tracking-[.16em] text-slate-600"><span>Execution</span><span>Owner</span><span>State</span></div>{filteredWork.map(item => <div key={item.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 border-b border-white/5 px-4 py-3.5 last:border-0"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`rounded-md px-1.5 py-0.5 text-[9px] font-bold ${item.priority === "P0" ? "bg-rose-400/10 text-rose-300" : "bg-amber-400/10 text-amber-300"}`}>{item.priority}</span><span className="truncate text-xs font-medium text-white">{item.title}</span></div><div className="mt-1 text-[10px] text-slate-600">{item.id} · Dept {item.department} · {item.value ?? "Execution"}</div></div><span className="hidden text-[10px] text-slate-400 sm:block">{item.owner}</span><span className="rounded-full bg-white/[.05] px-2 py-1 text-[9px] text-slate-400">{item.status}</span></div>)}{filteredWork.length === 0 && <div className="p-8 text-center text-xs text-slate-500">No execution items match this view.</div>}</div></section>

          <section className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-white">Revenue engine</div><div className="mt-1 text-xs text-slate-500">Lead → settlement</div></div><ArrowUpRight size={17} className="text-emerald-400"/></div><div className="mt-5 space-y-3">{[["Leads","1,284","100%"],["Opportunities","184","62%"],["Buyers","73","39%"],["Deals","27","21%"],["Contracts","19","15%"],["Delivery","11","9%"],["Revenue","₹38.6L","—"]].map(([label,value,width]) => <div key={label}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-slate-400">{label}</span><span className="text-slate-300">{value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400/70 to-blue-500/70" style={{width: width === "—" ? "100%" : width}}/></div></div>)}</div></section>
        </div>

        <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-white/8 bg-white/[.025] p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-white">Department pulse</div><div className="mt-1 text-xs text-slate-500">Current operating health across the organization</div></div><button className="text-xs text-slate-500 hover:text-white">View all</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{departments.slice(1).map(([id,name], i) => <button key={id} onClick={() => setActive(id)} className="flex items-center gap-3 rounded-xl border border-white/6 bg-white/[.02] p-3 text-left hover:bg-white/[.045]"><span className="text-[9px] font-semibold text-slate-600">{id}</span><span className="flex-1 text-xs text-slate-300">{name}</span><span className={`h-1.5 w-1.5 rounded-full ${i % 5 === 3 ? "bg-amber-400" : "bg-emerald-400"}`}/><ChevronRight size={13} className="text-slate-700"/></button>)}</div></section><section className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="text-sm font-semibold text-white">Control status</div><div className="mt-4 space-y-3">{[["Identity & RBAC",ShieldCheck,"Verified"],["Data layer",Database,"Ready"],["Automation",Network,"14 active"],["Verification",FileCheck2,"Healthy"],["SLA / runtime",Gauge,"99.98%"]].map(([label,Icon,status]) => <div key={label as string} className="flex items-center gap-3 rounded-xl bg-white/[.025] px-3 py-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/[.05]"><Icon size={14} className="text-slate-400"/></span><span className="flex-1 text-xs text-slate-300">{label as string}</span><span className="text-[10px] text-emerald-400">{status as string}</span></div>)}</div></section></div>

        <section className="mt-5 rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-white">Execution timeline</div><div className="mt-1 text-xs text-slate-500">NEW → ROUTED → ACCEPTED → IN PROGRESS → READY → VERIFIED → RESULT</div></div><div className="flex items-center gap-2"><div className="relative"><Search size={13} className="absolute left-3 top-2.5 text-slate-600"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter execution" className="w-48 rounded-lg border border-white/8 bg-black/20 py-2 pl-8 pr-3 text-xs text-white outline-none placeholder:text-slate-600"/></div><button className="grid h-8 w-8 place-items-center rounded-lg border border-white/8"><Filter size={13}/></button><button className="grid h-8 w-8 place-items-center rounded-lg border border-white/8"><Plus size={14}/></button></div></div><div className="mt-4 grid gap-2 md:grid-cols-4"><div className="rounded-xl border border-white/6 p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">In progress</div><div className="mt-2 text-lg font-semibold text-white">18</div><div className="mt-1 text-[10px] text-slate-500">6 revenue-impacting</div></div><div className="rounded-xl border border-white/6 p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">Ready</div><div className="mt-2 text-lg font-semibold text-white">9</div><div className="mt-1 text-[10px] text-slate-500">3 awaiting verification</div></div><div className="rounded-xl border border-white/6 p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">Verified</div><div className="mt-2 text-lg font-semibold text-white">41</div><div className="mt-1 text-[10px] text-slate-500">100% evidence captured</div></div><div className="rounded-xl border border-white/6 p-3"><div className="text-[9px] uppercase tracking-wider text-slate-600">Decisions</div><div className="mt-2 text-lg font-semibold text-white">4</div><div className="mt-1 text-[10px] text-slate-500">Founder attention required</div></div></div></section>
      </div>
    </main>

    {commandOpen && <div className="fixed inset-0 z-50 bg-black/70 p-4 backdrop-blur-sm" onClick={() => setCommandOpen(false)}><div className="mx-auto mt-[12vh] max-w-2xl overflow-hidden rounded-2xl border border-white/10 bg-[#0c1016] shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-white/8 px-4 py-4"><Search size={17} className="text-slate-500"/><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Command the business center…" className="flex-1 bg-transparent text-sm text-white outline-none placeholder:text-slate-600"/><kbd className="rounded border border-white/10 px-2 py-1 text-[9px] text-slate-500">ESC</kbd></div><div className="p-3"><button onClick={() => { setCommandOpen(false); setActive("00"); }} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/[.05]"><Sparkles size={16} className="text-cyan-300"/><div><div className="text-xs font-medium text-white">Open Founder Command</div><div className="text-[10px] text-slate-500">Executive decisions, priorities and blockers</div></div></button><button onClick={() => { setCommandOpen(false); setActive("02"); }} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/[.05]"><CircleDollarSign size={16} className="text-emerald-300"/><div><div className="text-xs font-medium text-white">Go to Revenue</div><div className="text-[10px] text-slate-500">P0 deals and money-now pipeline</div></div></button><button onClick={() => { setCommandOpen(false); setActive("08"); }} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/[.05]"><Bot size={16} className="text-violet-300"/><div><div className="text-xs font-medium text-white">Open AI Workforce</div><div className="text-[10px] text-slate-500">Agents, automation and verification</div></div></button></div></div></div>}
  </div>;
}
