import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
type Point = { date: string; revenue: number; refunds: number; successfulPayments: number };
type Metrics = { grossRevenue:number; refundedAmount:number; netRevenue:number; activeSubscriptions:number; monthlyRecurringRevenue:number; successfulPayments:number; refundEvents:number; successToRefundRatio:number|null; creatorPayout:number; platformCollection:number; allocationTotal:number };
type Payload = { metrics: Metrics; series: Point[]; generatedAt: string };
const zero: Metrics = {grossRevenue:0,refundedAmount:0,netRevenue:0,activeSubscriptions:0,monthlyRecurringRevenue:0,successfulPayments:0,refundEvents:0,successToRefundRatio:0,creatorPayout:0,platformCollection:0,allocationTotal:0};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const placeholder=<div className="rounded-3xl border border-white/10 bg-[#070914] p-8 text-white"><div className="grid h-64 place-items-center rounded-2xl border border-dashed border-cyan-400/20 bg-[linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:24px_24px]"><div className="text-center"><p className="text-sm font-medium text-white/70">Ledger telemetry is initializing</p><p className="mt-1 text-xs text-white/35">Verified Razorpay events will populate the matrix automatically.</p></div></div></div>;
function linePoints(data:Point[]){const max=Math.max(1,...data.map(x=>x.revenue));return data.map((x,i)=>`${data.length<2?380:i*760/(data.length-1)},${210-(x.revenue/max)*190}`).join(" ")}
export default function PaymentCharts(){
 const [data,setData]=useState<Payload>({metrics:zero,series:[],generatedAt:""}); const [busy,setBusy]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{let dead=false;(async()=>{const {data:s,error:e}=await supabase.auth.getSession();const token=s.session?.access_token;if(e||!token){if(!dead){setError("Admin session required");setBusy(false)};return}try{const r=await fetch("/api/analytics/payments",{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"},cache:"no-store"});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Unable to load payment analytics");if(!dead)setData(b)}catch(x){if(!dead)setError(x instanceof Error?x.message:"Unable to load payment analytics")}finally{if(!dead)setBusy(false)}})();return()=>{dead=true}},[]);
 const m=data.metrics||zero; const pts=useMemo(()=>linePoints(data.series||[]),[data.series]); const max=Math.max(1,m.creatorPayout,m.platformCollection); const cw=m.creatorPayout/max*100, pw=m.platformCollection/max*100;
 if(busy)return placeholder;if(error)return <div className="rounded-3xl border border-rose-400/15 bg-[#0a0710] p-8 text-white"><p className="font-semibold text-rose-200">Payment telemetry unavailable</p><p className="mt-2 text-xs text-white/45">{error}. The ledger remains isolated until a verified admin session is available.</p></div>;if(!data.series?.length)return placeholder;
 return <section className="space-y-6 rounded-[2rem] border border-white/10 bg-[#070914] p-6 text-white shadow-2xl shadow-black/50 md:p-8">
  <header className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[0.32em] text-cyan-300/60">Razorpay Ledger / Live Telemetry</p><h2 className="mt-2 text-2xl font-semibold">Payment intelligence</h2><p className="mt-1 text-xs text-white/40">30-day verified event window · server-authorized admin scope</p></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/5 px-3 py-1 text-[10px] text-emerald-200/80">LIVE LEDGER</span></header>
  <div className="grid gap-3 md:grid-cols-4">{[["Gross revenue",money(m.grossRevenue)],["Net revenue",money(m.netRevenue)],["Active subscriptions",m.activeSubscriptions.toLocaleString("en-IN")],["MRR",money(m.monthlyRecurringRevenue)]].map(([l,v])=><article key={l} className="rounded-2xl border border-white/8 bg-white/[0.035] p-5"><p className="text-[10px] uppercase tracking-[0.2em] text-white/35">{l}</p><p className="mt-3 text-2xl font-semibold">{v}</p></article>)}</div>
  <article className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><div className="flex justify-between"><div><h3 className="text-sm font-semibold">Revenue trajectory</h3><p className="mt-1 text-[11px] text-white/35">Captured payments across the last 30 days</p></div><div className="text-[10px] text-white/35">Refunds {money(m.refundedAmount)}</div></div><div className="mt-5 rounded-xl border border-white/5 bg-black/20 p-3"><svg viewBox="0 0 760 240" className="h-64 w-full"><line x1="0" x2="760" y1="210" y2="210" stroke="currentColor" className="text-white/5"/><polyline points={pts} fill="none" stroke="currentColor" strokeWidth="3" className="text-cyan-300" strokeLinecap="round" strokeLinejoin="round"/></svg></div></article>
  <div className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><h3 className="text-sm font-semibold">Deal allocation</h3><p className="mt-1 text-[11px] text-white/35">Creator payout vs platform collection</p><div className="mt-6 space-y-5"><div><div className="mb-2 flex justify-between text-xs"><span className="text-white/60">Creator payout</span><strong>{money(m.creatorPayout)}</strong></div><div className="h-3 rounded-full bg-white/5"><div className="h-full rounded-full bg-cyan-300/80" style={{width:`${cw}%`}}/></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-white/60">Platform collection</span><strong>{money(m.platformCollection)}</strong></div><div className="h-3 rounded-full bg-white/5"><div className="h-full rounded-full bg-violet-300/80" style={{width:`${pw}%`}}/></div></div>{!m.allocationTotal&&<p className="rounded-xl border border-amber-300/10 bg-amber-300/5 p-3 text-[11px] text-amber-100/50">Allocation metadata is absent; no split values are inferred.</p>}</div></article>
  <article className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><h3 className="text-sm font-semibold">Settlement quality</h3><p className="mt-1 text-[11px] text-white/35">Success-to-refund event ratio</p><p className="mt-7 text-5xl font-semibold">{m.successToRefundRatio===null?"∞":m.successToRefundRatio.toFixed(2)}×</p><div className="mt-6 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-white/[0.035] p-4">Successful<p className="mt-1 text-lg font-semibold">{m.successfulPayments}</p></div><div className="rounded-xl bg-white/[0.035] p-4">Refund events<p className="mt-1 text-lg font-semibold">{m.refundEvents}</p></div></div></article></div>
  <p className="text-[10px] text-white/25">Last server snapshot: {data.generatedAt?new Date(data.generatedAt).toLocaleString("en-IN"):"—"}</p>
 </section>;
}
