-- StreamVista Film Metadata Entry layer.
-- Extends the canonical Film OS project graph without replacing it.

create table if not exists public.film_metadata (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null unique references public.film_projects(id) on delete cascade,
  canonical_title text not null,
  alternate_title text,
  release_status text not null default 'unknown' check (release_status in ('released','not_released','unknown')),
  release_date date,
  language text,
  genre text,
  runtime_minutes integer,
  certification text,
  director text,
  producer text,
  production_house text,
  lead_cast text,
  synopsis text,
  poster_url text,
  trailer_url text,
  ott_platform text,
  ott_release_date date,
  theatrical_release boolean,
  territory text,
  rights_owner text,
  chain_of_title_status text not null default 'pending' check (chain_of_title_status in ('verified','pending','failed')),
  rights_type text,
  exclusivity text,
  rights_start date,
  rights_end date,
  buyer_status text not null default 'unlisted',
  screener_status text not null default 'not_available',
  qc_status text not null default 'not_tested',
  metadata_status text not null default 'draft' check (metadata_status in ('draft','review','verified','locked')),
  verification_source text,
  verification_date date,
  confidence text not null default 'low' check (confidence in ('high','medium','low')),
  asking_price numeric,
  minimum_guarantee numeric,
  revenue_share numeric,
  license_fee numeric,
  territory_price numeric,
  buyer_restrictions text,
  subtitle_availability text,
  dubbing_availability text,
  master_format text,
  master_storage_location text,
  watermarked_screener_url text,
  admin_approval text not null default 'pending' check (admin_approval in ('pending','approved','rejected')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists film_metadata_release_status_idx on public.film_metadata(release_status);
create index if not exists film_metadata_title_idx on public.film_metadata(canonical_title);
create index if not exists film_metadata_metadata_status_idx on public.film_metadata(metadata_status);
