-- 1. Users & RBAC

CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) UNIQUE NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE permissions (
    permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR2(100) UNIQUE NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE role_permissions (
    role_id NUMBER REFERENCES roles(role_id),
    permission_id NUMBER REFERENCES permissions(permission_id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255),
    phone VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id NUMBER REFERENCES users(user_id),
    role_id NUMBER REFERENCES roles(role_id),
    PRIMARY KEY (user_id, role_id)
);

-- 2. Product Catalog

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER REFERENCES categories(category_id),
    category_name VARCHAR2(100) NOT NULL,
    slug VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE brands (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL,
    logo_url VARCHAR2(255)
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id NUMBER REFERENCES brands(brand_id),
    category_id NUMBER REFERENCES categories(category_id),
    sku VARCHAR2(50) UNIQUE NOT NULL,
    part_number VARCHAR2(50),
    oem_number VARCHAR2(50),
    product_name VARCHAR2(255) NOT NULL,
    description CLOB,
    price NUMBER(12, 2) NOT NULL,
    tax_rate NUMBER(5, 2) DEFAULT 18.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicle_compatibility (
    compatibility_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES products(product_id),
    make VARCHAR2(100),
    model VARCHAR2(100),
    year_start NUMBER(4),
    year_end NUMBER(4),
    engine_type VARCHAR2(100)
);

-- 3. Inventory & Warehouse

CREATE TABLE warehouses (
    warehouse_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(255)
);

CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id NUMBER REFERENCES warehouses(warehouse_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER DEFAULT 0,
    reserved_quantity NUMBER DEFAULT 0,
    bin_location VARCHAR2(50)
);

CREATE TABLE stock_movements (
    movement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id NUMBER REFERENCES inventory(inventory_id),
    movement_type VARCHAR2(20), -- 'IN', 'OUT', 'TRANSFER', 'ADJUST'
    quantity NUMBER NOT NULL,
    reference_id NUMBER, -- Order ID or Purchase Order ID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Orders & Payments

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    customer_type VARCHAR2(10) DEFAULT 'B2C', -- 'B2B', 'B2C'
    gstin VARCHAR2(15),
    company_name VARCHAR2(255)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES customers(customer_id),
    total_amount NUMBER(12, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER NOT NULL,
    unit_price NUMBER(12, 2) NOT NULL
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    transaction_id VARCHAR2(100) UNIQUE,
    payment_method VARCHAR2(50),
    amount NUMBER(12, 2) NOT NULL,
    status VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
